name: Run Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes UTC
  workflow_dispatch:  # Optional: lets you run it manually from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # optional

    - name: Run your script
      run: python main.py
